name: Update Go Dependencies

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every Sunday at 02:00 UTC
  workflow_dispatch:     # Allow manual triggering

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Update dependencies
        run: |
          go get -u ./...
          go mod tidy

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add go.mod go.sum
          git commit -m "chore: update dependencies" || echo "No changes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

